### ISSUE TITLE
minor: view source code ( view on Github) button is only available after signing up and/on log in.

### ISSUE THREAD

**Issue by 0verread** [alanagoyal/docbase#2]
![Screenshot 2023-05-30 at 9 03 26 PM](https://github.com/alanagoyal/docbase/assets/97605913/45d3f556-1a09-4484-9c00-237796689b86)

View source code button should be visible on the landing page.  This is a minor change. 

@alanagoyal I can take care of this if you haven't started working on this.

**Comment by alanagoyal** [comment]
yeah please do!
