### ISSUE TITLE
Not able to fetch data from supabase db

### ISSUE THREAD

**Issue by piyush101** [alanagoyal/docbase#4]
I have given all(read, insert, delete) accesses to all the three tables. But still i am not able to fetch(read) data from any of the table. 
I have checked supabase_url, supabase_anon_key . Everything is ok.

Please help , if you have also encountered with the same issues. If i need to do something else. I am looking forward to contribute more to this project.

**Comment by 0verread** [comment]
can you post ss of the error? @piyush101

**Comment by piyush101** [comment]
@0verread Here is the error
`'TypeError: fetch failed
    at Object.fetch (/Users/piyushgupta/Downloads/docbase/node_modules/next/dist/compiled/undici/index.js:1:26669)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)'`
    
    Here is attachment of error . Please help
    
    
<img width="1512" alt="Screenshot 2023-06-10 at 5 08 17 PM" src="https://github.com/alanagoyal/docbase/assets/26116219/bf15162b-b6c9-420b-84b9-8309b529da05">

**Comment by 0verread** [comment]
@piyush101 it seems like an error from the superbase side. have you tried to delete all tables and do the migration again? try to follow the README instruction.
