### ISSUE TITLE
Hangs at "wait compiling /page (client and server)..."

### ISSUE THREAD

**Issue by KeithHanson** [alanagoyal/docbase#5]
![image](https://github.com/alanagoyal/docbase/assets/3627/5a12776e-3c99-470e-b918-d909afb340c8)

I've followed the readme exactly as instructed. .env.local looks good, supabase tables are there after running your SQL. 

RLS is off, so anon key access for read/write. In the screenshot above I only gave the server 2 minutes to respond, but prior to taking the screenshot, I let it run for a full 15 minutes before deciding to make an issue :) 

Any help would be greatly appreciated!

**Comment by 0verread** [comment]
This is NextJS issue. Dev mode compilation takes a lot of time. they are working on it ( probably) see [this](https://github.com/vercel/next.js/issues/48748)
